<a href="https://colab.research.google.com/github/ganeshkumar1887/Machine-Learning-/blob/main/Reinforcement%20Learning/Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
states = 6
actions = 2

In [3]:
action_names = ["Left","Right"]
state_names = ["S0","S1","S2","S3","S4","S5"]

In [4]:
Q = np.zeros((states, actions))
print(Q)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

In [5]:
alpha = 0.1      # learning rate
gamma = 0.9      # discount factor
epsilon = 0.2    # exploration rate
episodes = 200

In [6]:
for episode in range(episodes):

    state = np.random.randint(0, states)

    for step in range(20):

        if np.random.rand() < epsilon:
            action = np.random.randint(actions)
        else:
            action = np.argmax(Q[state])

        if action == 0:
            next_state = max(0, state-1)
        else:
            next_state = min(states-1, state+1)

        reward = 10 if next_state == 5 else 0

        Q[state, action] = Q[state, action] + alpha * (
            reward + gamma * np.max(Q[next_state]) - Q[state, action]
        )

        state = next_state

    # print Q-table every 200 episodes
    if episode % 10 == 0:
        print("\nEpisode:", episode)
        df = pd.DataFrame(Q, columns=action_names)
        df.index = state_names
        display(df)

Episode: 0

    Left  Right
S0   0.0    0.0
S1   0.0    0.0
S2   0.0    0.0
S3   0.0    0.0
S4   0.0    0.0
S5   0.0    0.0

Episode: 10

        Left      Right
S0  0.000000   0.000000
S1  0.000000   0.000000
S2  0.000000   0.135127
S3  0.000000   3.107533
S4  0.000000  22.972770
S5  2.576477  57.011099

Episode: 20

         Left      Right
S0   0.000000   0.000000
S1   0.000000   0.000000
S2   0.000000   2.790909
S3   0.000000  24.933563
S4   3.212553  71.347495
S5  38.745039  83.286606

Episode: 30

         Left      Right
S0   0.000000   0.000000
S1   0.000000   0.000000
S2   0.000000  14.122957
S3   1.601921  55.470544
S4  17.472285  89.222859
S5  64.080625  95.520030

Episode: 40

         Left      Right
S0   0.000000   0.000000
S1   0.000000   0.000000
S2   0.000000  14.122957
S3   1.601921  63.099073
S4  24.099586  95.399081
S5  77.669671  97.783138

Episode: 50

         Left      Right
S0   0.000000   0.000000
S1   0.000000   0.000000
S2   0.000000  19.406739
S3   2.712795  78.250460
S4  38.641726  98.678617
S5  86.134861  99.251245

Episode: 60

         Left      Right
S0   0.000000   0.000000
S1   0.000000   4.594002
S2   0.000000  41.391606
S3   2.712795  84.472816
S4  48.211065  99.434287
S5  88.156506  99.766642

Episode: 70

         Left      Right
S0   0.000000   1.000341
S1   0.000000  11.114903
S2   0.000000  51.052835
S3   2.712795  87.212828
S4  53.687716  99.854813
S5  89.477343  99.921182

Episode: 80

         Left      Right
S0   0.000000   3.611462
S1   0.199273  21.661089
S2   0.000000  62.735782
S3   2.712795  88.977490
S4  60.583530  99.963499
S5  89.879851  99.978660

Episode: 90

         Left      Right
S0   0.000000   9.606101
S1   0.199273  34.450504
S2   1.949498  68.772763
S3   2.712795  89.500398
S4  64.338023  99.989263
S5  89.964338  99.994827

Episode: 100

         Left      Right
S0   1.531856  19.382874
S1   1.282533  47.444404
S2   1.949498  76.092927
S3  19.810698  89.803183
S4  67.444075  99.996614
S5  89.986850  99.998655

Episode: 110

         Left      Right
S0   1.531856  24.002474
S1   3.108593  54.960741
S2  10.388959  78.053747
S3  24.720718  89.914356
S4  69.996219  99.999050
S5  89.995115  99.999684

Episode: 120

         Left      Right
S0   1.531856  24.002474
S1   3.108593  60.522313
S2  10.388959  79.703613
S3  29.343655  89.966576
S4  69.996219  99.999831
S5  89.999165  99.999915

Episode: 130

         Left      Right
S0   1.531856  30.244344
S1   3.108593  64.477661
S2  10.388959  80.369373
S3  33.613576  89.985557
S4  71.094619  99.999953
S5  89.999753  99.999980

Episode: 140

         Left      Right
S0   1.531856  35.659725
S1   3.108593  66.643571
S2  10.388959  80.724149
S3  41.022945  89.995905
S4  73.777371  99.999986
S5  89.999870  99.999995

Episode: 150

         Left      Right
S0   1.531856  42.446488
S1   3.108593  69.133370
S2  10.388959  80.880160
S3  44.194279  89.998955
S4  76.260647  99.999997
S5  89.999963  99.999999

Episode: 160

         Left       Right
S0   1.531856   46.236487
S1   6.795879   70.132062
S2  10.388959   80.928933
S3  47.056100   89.999671
S4  77.890352   99.999999
S5  89.999993  100.000000

Episode: 170

         Left       Right
S0   1.531856   47.949215
S1  10.277575   70.649981
S2  10.388959   80.962121
S3  49.634731   89.999842
S4  78.481150  100.000000
S5  89.999998  100.000000

Episode: 180

         Left       Right
S0   1.531856   49.550684
S1  13.565247   71.250837
S2  24.860923   80.977582
S3  54.050156   89.999932
S4  79.163732  100.000000
S5  90.000000  100.000000

Episode: 190

         Left       Right
S0   1.531856   53.565440
S1  13.565247   72.017330
S2  24.860923   80.990329
S3  55.933815   89.999976
S4  79.512617  100.000000
S5  90.000000  100.000000